---
# tasks file for ansible-role-proxy-settings

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]

- name: "Include tasks from env playbook"
  ansible.builtin.include_tasks: env.yaml

- name: "Include tasks from apt playbook"
  ansible.builtin.include_tasks: apt.yaml
  when:
    - ansible_facts['pkg_mgr'] == 'apt'

- name: "Include tasks from subscription-manager playbook"
  ansible.builtin.include_tasks: subscription-manager.yaml
  when:
    - ansible_facts['distribution'] == 'RedHat'

- name: "Include tasks from yum playbook"
  ansible.builtin.include_tasks: yum.yaml
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Include tasks from dnf playbook"
  ansible.builtin.include_tasks: dnf.yaml
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Include tasks from centos playbook"
  ansible.builtin.include_tasks: centos.yaml
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['distribution_major_version'] <= '7'
