---
# tasks file for ansible-role-proxy-settings

- name: "Include tasks from apt playbook"
  ansible.builtin.include_tasks: apt.yaml
  when: ansible_facts['os_family'] == 'Debian'

- name: "Include tasks from yum playbook"
  ansible.builtin.include_tasks: yum.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] <= '7'
